# modules/youtube_downloader/module_settings.yaml
# Настройки модуля YouTube Downloader

# Ограничения загрузки
max_downloads_per_day: 10
max_file_size_mb: 100
allow_playlists: false

# Настройки качества по умолчанию
default_video_quality: "720p"
default_audio_quality: "192"

# Настройки хранения файлов
download_directory: "project_data/downloads/youtube"
auto_cleanup_days: 7  # Автоматически удалять файлы старше N дней
keep_failed_downloads: false

# Настройки уведомлений
notify_on_completion: true
notify_on_failure: true

# Дополнительные настройки yt-dlp
extract_thumbnails: false
extract_subtitles: false
write_info_json: false
