# config.yaml - Настройки SwiftDevBot
# Чувствительные данные (токены, ID) хранятся в .env файле

# Настройки администратора
admin:
  auto_create_super_admin: true
  # super_admin_telegram_id теперь в .env (SUPER_ADMIN_TELEGRAM_ID)

# Настройки бота
bot:
  # token теперь в .env (BOT_TOKEN)
  username: SwiftDev_Bot
  polling_timeout: 30

# Настройки кэша
cache:
  backend: memory  # memory или redis
  ttl: 3600
  # redis_url теперь в .env (REDIS_URL)

# Настройки базы данных
database:
  type: sqlite  # sqlite, postgresql, mysql
  echo: false
  sqlite_path: Database_files/sdb.db
  # pg_dsn и mysql_dsn теперь в .env

# Настройки веб-сервера
features:
  web_download_server:
    enabled: true
    host: 0.0.0.0
    port: 8080
    # external_host и external_port теперь в .env

# Настройки логирования
logging:
  console_logging: true
  file_logging: true
  level: INFO
  rotation_size: "100 MB"
  retention_period: "3 months"

# Настройки интернационализации
i18n:
  default_locale: en
  available_locales: [en, ua, ru]

# Настройки модулей
modules:
  auto_load: true
  repo_index_url: "https://raw.githubusercontent.com/soverxos/SwiftDevBot-Modules/main/modules_index.json"

# Настройки мониторинга
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_enabled: true
