# Шаблон конфигурации SwiftDevBot (config.yaml)
# Этот файл используется как шаблон для команды 'sdb config init'.
# Рабочая конфигурация пользователя находится в project_data/Config/core_settings.yaml

db:
  type: "sqlite"  # Тип базы данных: "sqlite", "postgresql", "mysql"
  # Путь к файлу SQLite, ОТНОСИТЕЛЬНО директории данных проекта (core.project_data_path)
  # sqlite_path: "Database_files/swiftdevbot.db" 
  # pg_dsn: "postgresql+asyncpg://user:pass@host:port/dbname" # DSN для PostgreSQL
  # mysql_dsn: "mysql+aiomysql://user:pass@host:port/dbname" # DSN для MySQL
  echo_sql: false # Логировать SQL-запросы SQLAlchemy (уровень DEBUG)

cache:
  # type: "memory" # Тип кэша: "memory", "redis"
  # redis_url: "redis://localhost:6379/0" # URL для Redis

telegram:
  # token: "ВАШ_ТЕЛЕГРАМ_ТОКЕН" # !!! РЕКОМЕНДУЕТСЯ УКАЗЫВАТЬ BOT_TOKEN В .env ФАЙЛЕ !!!
  polling_timeout: 30 # Таймаут для long polling (секунды)

module_repo:
  index_url: "https://raw.githubusercontent.com/soverxos/SwiftDevBot-Modules/main/modules_index.json" # URL к индексу модулей

core:
  # Путь к директории данных проекта. Может быть абсолютным или относительным к корню проекта.
  project_data_path: "./project_data" 
  super_admins: [] # Список Telegram ID супер-администраторов, например: [123456789, 9876543210]
  
  # Путь к файлу со списком активных модулей, ОТНОСИТЕЛЬНО директории данных проекта
  enabled_modules_config_path: "Config/enabled_modules.json" 
  
  # Настройки логирования
  log_level: "INFO" # Уровень: TRACE, DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true # Писать ли логи в файл
  # Базовая директория для структурированных логов (относительно project_data_path).
  # Файлы будут создаваться в подпапках YYYY/MM-MonthName/DD/HH_sdb.log
  log_structured_dir: "Logs" 
  # Ротация для каждого часового файла лога по размеру.
  log_rotation_size: "100 MB" 
  # Как долго хранить структурированные логи (например, "30 days", "3 months").
  # Реализуется отдельной задачей очистки внутри бота.
  log_retention_period_structured: "3 months" 

  sdb_version: "0.1.0" # Версия ядра (можно не указывать здесь, если берется из дефолта модели)
  setup_bot_commands_on_startup: true # Устанавливать ли команды бота при старте

  i18n:
    # Путь к директории с файлами переводов (относительно корня проекта)
    locales_dir: "locales" 
    domain: "bot"
    default_locale: "en"
    available_locales: ["en", "ua"]