admin:
  auto_create_super_admin: true
cache:
  backend: memory
  ttl: 3600
  type: memory
core:
  log_level: INFO
  log_to_file: true
  setup_bot_commands_on_startup: true
  super_admins:
  - 7847397229
database:
  echo: false
  echo_sql: false
  sqlite_path: Database_files/sdb.db
  type: sqlite
features:
  web_download_server:
    enabled: true
    host: 0.0.0.0
    port: 8080
i18n:
  available_locales:
  - en
  - ua
  - ru
  default_locale: en
logging:
  console_logging: true
  file_logging: true
  level: INFO
  retention_period: 3 months
  rotation_size: 100 MB
modules:
  auto_load: true
  repo_index_url: https://raw.githubusercontent.com/soverxos/SwiftDevBot-Modules/main/modules_index.json
monitoring:
  enabled: true
  health_check_enabled: true
  metrics_port: 9090
telegram:
  polling_timeout: 30
  token: 8307984765:AAEu416t_YsdZQDmyBNtoeK_9btGb4YNUwg
  username: SwiftDev_Bot
